server:
  port: 8084

spring:
  data:
    mongodb:
      host: 10.2.24.232
      port: 8017
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.2.25.123/ggrdattest
    username: greescmdb2
    password: passwd
  application:
    name: resource-server
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
minio:
  url: http://10.2.24.234:9003
  access-key: admin
  secret-key: 12345678
  bucket-name: test
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key
        key-value: internet_plus